### ISSUE TITLE
Is there an example about how to export onnx model  from pytorch?

### ISSUE THREAD

**Issue by vraivon** [JosephChenHub/CenterNet-TensorRT#1]
Is there an example about how you export onnx model  from pytorch  with custom layer(bilinear upsample in this project)?
such as F.interpolate(input,size, mode='bilinear', align_corners=True)

**Comment by JosephChenHub** [comment]
for custom operators, u should register the operator in PyTorch. see [torch.onnx](https://pytorch.org/docs/stable/onnx.html)

**Comment by JosephChenHub** [comment]
> Is there an example about how you export onnx model from pytorch with custom layer(bilinear upsample in this project)?
> such as F.interpolate(input,size, mode='bilinear', align_corners=True)

one example can be found at https://github.com/JosephChenHub/CenterNet-TensorRT/blob/master/onnx-tensorrt/plugin/my_upsampling.py
