### ISSUE TITLE
the error of the builded step of centernet-tensorrt

### ISSUE THREAD

**Issue by CaptainJohansson** [JosephChenHub/CenterNet-TensorRT#10]
when i build the centernet-tensorrt, i got an error shown in the below.
/CenterNet-TensorRT/src/decode.cu(170): error: identifier "compAndSwap" is undefined
          detected during instantiation of "void bitonicLocalSortIndices(T *, size_t *, int, size_t, size_t, int) [with T=float]"

**Comment by CaptainJohansson** [comment]
in decode.cu(170), i change the compAndSwap to compAndSwapIndices, then i finish the build of centernet-tensorrt. i want to know this change is right for your code?

**Comment by CaptainJohansson** [comment]
不好意思，我又遇到一个问题。当我在onnx->tensorrt engine过程中设置batch_size=32，在pose_infe.cpp中运行得到的binding维度打印结果还是batch=1，打印结果如下：
Create the engine from weights/multi_pose.trt successfully!
i=0 tensor's name:input dim:(1,3,512,512) size:786432
i=1 tensor's name:wh dim:(1,2,128,128) size:32768
i=2 tensor's name:hps dim:(1,34,128,128) size:557056
i=3 tensor's name:reg dim:(1,2,128,128) size:32768
i=4 tensor's name:hp_offset dim:(1,2,128,128) size:32768
i=5 tensor's name:hm dim:(1,1,128,128) size:16384
i=6 tensor's name:hm_hp dim:(1,17,128,128) size:278528
这个batch的错误会导致后面CUDA内存分配出现问题。请问您有什么好的想法吗？

**Comment by JosephChenHub** [comment]
> 不好意思，我又遇到一个问题。当我在onnx->tensorrt engine过程中设置batch_size=32，在pose_infe.cpp中运行得到的binding维度打印结果还是batch=1，打印结果如下：
> Create the engine from weights/multi_pose.trt successfully!
> i=0 tensor's name:input dim:(1,3,512,512) size:786432
> i=1 tensor's name:wh dim:(1,2,128,128) size:32768
> i=2 tensor's name:hps dim:(1,34,128,128) size:557056
> i=3 tensor's name:reg dim:(1,2,128,128) size:32768
> i=4 tensor's name:hp_offset dim:(1,2,128,128) size:32768
> i=5 tensor's name:hm dim:(1,1,128,128) size:16384
> i=6 tensor's name:hm_hp dim:(1,17,128,128) size:278528
> 这个batch的错误会导致后面CUDA内存分配出现问题。请问您有什么好的想法吗？

Currently , the tool `onnx-tensorrt` in this repo. does not support the dynamic shape, which means the batch size was determined when converting the onnx model. However, I do successfully implement a version that supports the dynamic shape, and I can give u some tips:
1. make sure that the version of TensorRT is 7.x .
2. modify the `main.cpp` in `onnx-tensorrt` , and u can refer to the TensorRT developer guide to see how to use the dynamic shape. 
3. once successfully converted the onnx model with dynamic shape into the engine, u just need to bind the dimension shape in the runtime and enjoy the speedup !

**Comment by JosephChenHub** [comment]
> in decode.cu(170), i change the compAndSwap to compAndSwapIndices, then i finish the build of centernet-tensorrt. i want to know this change is right for your code?

u are right. this is a little syntax bug.

**Comment by CaptainJohansson** [comment]
> > 不好意思，我又遇到一个问题。当我在onnx->tensorrt engine过程中设置batch_size=32，在pose_infe.cpp中运行得到的binding维度打印结果还是batch=1，打印结果如下：
> > Create the engine from weights/multi_pose.trt successfully!
> > i=0 tensor's name:input dim:(1,3,512,512) size:786432
> > i=1 tensor's name:wh dim:(1,2,128,128) size:32768
> > i=2 tensor's name:hps dim:(1,34,128,128) size:557056
> > i=3 tensor's name:reg dim:(1,2,128,128) size:32768
> > i=4 tensor's name:hp_offset dim:(1,2,128,128) size:32768
> > i=5 tensor's name:hm dim:(1,1,128,128) size:16384
> > i=6 tensor's name:hm_hp dim:(1,17,128,128) size:278528
> > 这个batch的错误会导致后面CUDA内存分配出现问题。请问您有什么好的想法吗？
> 
> Currently , the tool `onnx-tensorrt` in this repo. does not support the dynamic shape, which means the batch size was determined when converting the onnx model. However, I do successfully implement a version that supports the dynamic shape, and I can give u some tips:
> 
> 1. make sure that the version of TensorRT is 7.x .
> 2. modify the `main.cpp` in `onnx-tensorrt` , and u can refer to the TensorRT developer guide to see how to use the dynamic shape.
> 3. once successfully converted the onnx model with dynamic shape into the engine, u just need to bind the dimension shape in the runtime and enjoy the speedup !

i use the original method to create the engine and  the code "int maxBatchsize = context->getEngine().getMaxBatchSize();" is applied to get the batchsize. after doing the above, i use batchsize to replace the "dim.d[0]" to get the right size. however, when i  take 3 same images as input, the output of this application is error. the first image input is correct but the other 2 image are error. do you comfirm your code with multi-batch inputs?

**Comment by JosephChenHub** [comment]
> > > 不好意思，我又遇到一个问题。当我在onnx->tensorrt engine过程中设置batch_size=32，在pose_infe.cpp中运行得到的binding维度打印结果还是batch=1，打印结果如下：
> > > Create the engine from weights/multi_pose.trt successfully!
> > > i=0 tensor's name:input dim:(1,3,512,512) size:786432
> > > i=1 tensor's name:wh dim:(1,2,128,128) size:32768
> > > i=2 tensor's name:hps dim:(1,34,128,128) size:557056
> > > i=3 tensor's name:reg dim:(1,2,128,128) size:32768
> > > i=4 tensor's name:hp_offset dim:(1,2,128,128) size:32768
> > > i=5 tensor's name:hm dim:(1,1,128,128) size:16384
> > > i=6 tensor's name:hm_hp dim:(1,17,128,128) size:278528
> > > 这个batch的错误会导致后面CUDA内存分配出现问题。请问您有什么好的想法吗？
> > 
> > 
> > Currently , the tool `onnx-tensorrt` in this repo. does not support the dynamic shape, which means the batch size was determined when converting the onnx model. However, I do successfully implement a version that supports the dynamic shape, and I can give u some tips:
> > 
> > 1. make sure that the version of TensorRT is 7.x .
> > 2. modify the `main.cpp` in `onnx-tensorrt` , and u can refer to the TensorRT developer guide to see how to use the dynamic shape.
> > 3. once successfully converted the onnx model with dynamic shape into the engine, u just need to bind the dimension shape in the runtime and enjoy the speedup !
> 
> i use the original method to create the engine and the code "int maxBatchsize = context->getEngine().getMaxBatchSize();" is applied to get the batchsize. after doing the above, i use batchsize to replace the "dim.d[0]" to get the right size. however, when i take 3 same images as input, the output of this application is error. the first image input is correct but the other 2 image are error. do you comfirm your code with multi-batch inputs?

Do u understand my reply?  u should manually modify the `main.cpp` in the `onnx-tensorrt`, and currently this version is not released.

**Comment by CaptainJohansson** [comment]
i modify the main.cpp in the onnx-tensorrt, but i meet another error. [PluginV2Ext]: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions. this error means i should change the DCNv2 plugin to inherit the PluginV2DynamicExt ? do you realize the plugin inheritig from PluginV2DynamicExt ?
