### ISSUE TITLE
plugin内存泄漏

### ISSUE THREAD

**Issue by egbertYeah** [JosephChenHub/CenterNet-TensorRT#12]
dcn_v2.cu的enqueue函数中存在内存泄漏
通过添加如下几行代码可以解决
CHECK_CUDA(cudaFree(d_col_buff));
CHECK_CUDA(cudaFree(d_w_buff));
CHECK_CUDA(cudaFree(d_o_buff));
望采纳！

**Comment by Wenboisstrong** [comment]
@CaptainJohansson  Hello, I think I encountered the problem you mentioned. Specifically, where is this code added, I am a cuda  new player thanks

**Comment by Wenboisstrong** [comment]
@CaptainJohansson 我在dcn_v2 enqueue 函数中最后加入此代码 来释放这些指针但是 似乎不起效果.(我是利用triton inference server 服务来 运行 Centernet ) 当我多个client 同时访问server 还是会报错.希望得到您的建议.谢谢

**Comment by CaptainJohansson** [comment]
我对triton这个服务器推理技术不熟悉，想问下没加这些代码之前您的程序是否运行正确或者您把报错贴出来，我看看

**Comment by Wenboisstrong** [comment]
cublasSgemm error occurred! /home/hc/git/testpt/CenterNet-TensorRT/onnx-tensorrt/plugin/DCN/dcn_v2.cu : 178, error_code:CUBLAS_STATUS_EXECUTION_FAILED, n:256, m:256, k:4608
cublasSgemm error occurred! /home/hc/git/testpt/CenterNet-TensorRT/onnx-tensorrt/plugin/DCN/dcn_v2.cu : 178, error_code:CUBLAS_STATUS_EXECUTION_FAILED, n:256, m:256, k:4608

这是报错提示: (对于triton 您可以理解为推理服务器 只需要将tensorrt的模型放置就可以指定文件夹下就可以建立一个docker 的服务 这个服务接受http grpc 请求 可以帮您推理模型 .我需要写一个前处理在py程序的客户端,然后通过 发送http请求 给docker服务,他会返回结果给 py程序从而输出结果 ) 问题出现在 当我一个线程的client 请求服务,可以良好运行.当我多个client 请求服务就会报错.您当时发现这个内存泄露 是和我遇到的错误提示相似么?谢谢您的答复

**Comment by CaptainJohansson** [comment]
这个内存泄漏运行是没有报错的，当时运行了一段时间才报的错。你这多个client请求服务engine是用的batchsize是1串行处理还是batchsize=N并行处理。

**Comment by Wenboisstrong** [comment]
batchsize=1

**Comment by CaptainJohansson** [comment]
那你怎么实现多个client请求服务的？每次的请求数据都是一样的吗？还是说你同时起来了多个检测engine？

**Comment by Wenboisstrong** [comment]
通过终端去调用我的py client.  多个终端同时启动 相当于 docker 服务器会接受 多个请求后排进队列 一一推理然后返回结果.

**Comment by Wenboisstrong** [comment]
之前我没有使用dcn 这个plugin 的时候 可以良好运行 当我尝试追求更好的准确率 :(

**Comment by CaptainJohansson** [comment]
![屏幕截图 2020-11-03 181242](https://user-images.githubusercontent.com/39177405/97972886-33091a80-1e00-11eb-949d-87b4f5431162.jpg)这个是我的修改位置

**Comment by Wenboisstrong** [comment]
感谢您的回复.我对比一下其他版本实现的dcn plugin.谢谢 @CaptainJohansson

**Comment by henbucuoshanghai** [comment]
本项目是检测box的那个centernet的trt部署?训练完就能跑通？
