### ISSUE TITLE
plugin-myupsample 有在centernet中使用吗？？

### ISSUE THREAD

**Issue by moerbenkaola** [JosephChenHub/CenterNet-TensorRT#13]
pytorch和转化的onnx模型都是反卷积实现，代码中有用plugin-myupsample替换反卷积吗？？

**Comment by JosephChenHub** [comment]
> pytorch和转化的onnx模型都是反卷积实现，代码中有用plugin-myupsample替换反卷积吗？？

this plugin was designed for semantic segmentation.
