### ISSUE TITLE
plugin-myupsample的使用是采用module-MyUpsampling在训练的时候替换掉原始的upsample,转onnx和tensorrt直接调用的自定义的MyUpsample OP？？

### ISSUE THREAD

**Issue by moerbenkaola** [JosephChenHub/CenterNet-TensorRT#14]
求问将centernet的的反卷积替换自定义的OP（Myupsample)中backward是没有实现的,无法直接训练？？

**Comment by JosephChenHub** [comment]
> 求问将centernet的的反卷积替换自定义的OP（Myupsample)中backward是没有实现的,无法直接训练？？

I place the `MyUpsample` here just because it might help someone who wants to convert the semantic segmentation models into TensorRT engines.  There is no `bilinear` interpolation used in the `CenterNet`.

**Comment by JosephChenHub** [comment]
If you manually replace the transpose convolution with the `F.interpolate` during the training, you can use this plugin to convert your model into the supported TensorRT engine.

**Comment by moerbenkaola** [comment]
> If you manually replace the transpose convolution with the `F.interpolate` during the training, you can use this plugin to convert your model into the supported TensorRT engine.

感谢大佬回答，centernet中没有bilinear，测试torch 中nn.upsamplingbilinear2d转onnx是转不出来的，我的意思是要把这个upsamplingbilinear2d换成Mysampling这个moule调用自定义的OP（Myupsample）训练，转onnx出来bilinear替换成Myupsample，转tensorrt也是调用Myupsample。还是说训练还是nn.upsamplingbilinear2d？？？主要是不太清楚onnx不支持的时候如何转
