### ISSUE TITLE
NMS On Detector Outputs

### ISSUE THREAD

**Issue by Sai-Venky** [JosephChenHub/CenterNet-TensorRT#17]
I am getting all the outputs from the detector. 
But I would like to add Non Maximal Suppression on top of the outputs based on the heatmap scores similar to the original implementation. In the original implementation, they did a max pooling and extracted the top k scores.
https://github.com/xingyizhou/CenterNet/blob/2b7692c377c6686fb35e473dac2de6105eed62c6/src/lib/models/decode.py#L9
https://github.com/JosephChenHub/CenterNet-TensorRT/blob/master/src/decode.cu#L359
Could you please let me know if there is any way to do this similarly here?
Thank You

**Comment by JosephChenHub** [comment]
> I am getting all the outputs from the detector.
> But I would like to add Non Maximal Suppression on top of the outputs based on the heatmap scores similar to the original implementation. In the original implementation, they did a max pooling and extracted the top k scores.
> https://github.com/xingyizhou/CenterNet/blob/2b7692c377c6686fb35e473dac2de6105eed62c6/src/lib/models/decode.py#L9
> https://github.com/JosephChenHub/CenterNet-TensorRT/blob/master/src/decode.cu#L359
> Could you please let me know if there is any way to do this similarly here?
> Thank You

Hi, you may refer to this implementation [nms](https://github.com/NVIDIA/TensorRT/tree/master/plugin/batchedNMSPlugin)

**Comment by Sai-Venky** [comment]
Thank You
