### ISSUE TITLE
编译onnx-tensorrt报错

### ISSUE THREAD

**Issue by FrankLiOnLine** [JosephChenHub/CenterNet-TensorRT#18]
我按照你的方法，先编译tensorRT plugin，指明路径后编译成功。下一步编译onnx-tensorrt的过程中，cmake阶段使用了和plugin部分cmake相同的路径，跑成功，但是在make阶段出现了下面的报错问题。主要有两类，一个是如下：

`/home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:1441:3: 错误：‘PROTOBUF_FUTURE_MUST_USE_RESULT’不是一个类型名PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_domain();  

/home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:1459:3: 错误：‘PROTOBUF_FUTURE_MUST_USE_RESULT’不是一个类型名PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_doc_string();   

/home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:1474:3: 错误：‘PROTOBUF_FUTURE_MUST_USE_RESULT’不是一个类型名PROTOBUF_FUTURE_MUST_USE_RESULT ::onnx2trt_onnx::GraphProto* release_graph();  

/home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:1661:3: 错误：‘PROTOBUF_FUTURE_MUST_USE_RESULT’不是一个类型名PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_key();  

/home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:1679:3: 错误：‘PROTOBUF_FUTURE_MUST_USE_RESULT’不是一个类型名PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_value(); `

还有一种如下：

`/home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:9207:87: 错误：成员函数‘onnx2trt_onnx::TypeProto_Spars
eTensor* onnx2trt_onnx::TypeProto::release_sparse_tensor_type()’未在类‘onnx2trt_onnx::TypeProto’中声明
 inline ::onnx2trt_onnx::TypeProto_SparseTensor* TypeProto::release_sparse_tensor_type() {

/home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:9280:74: 错误：成员函数‘onnx2trt_onnx::TypeProto_Opaqu
e* onnx2trt_onnx::TypeProto::release_opaque_type()’未在类‘onnx2trt_onnx::TypeProto’中声明
 inline ::onnx2trt_onnx::TypeProto_Opaque* TypeProto::release_opaque_type() {

/home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:9373:51: 错误：成员函数‘std::string* onnx2trt_onnx::Ty
peProto::release_denotation()’未在类‘onnx2trt_onnx::TypeProto’中声明
 inline std::string* TypeProto::release_denotation() {

/home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:9443:56: 错误：成员函数‘std::string* onnx2trt_onnx::Op
eratorSetIdProto::release_domain()’未在类‘onnx2trt_onnx::OperatorSetIdProto’中声明
 inline std::string* OperatorSetIdProto::release_domain() {`

这个看着像是onnx-tensorrt里面缺少头文件，请问po主怎么解决这个问题的啊

**Comment by JosephChenHub** [comment]
> 我按照你的方法，先编译tensorRT plugin，指明路径后编译成功。下一步编译onnx-tensorrt的过程中，cmake阶段使用了和plugin部分cmake相同的路径，跑成功，但是在make阶段出现了下面的报错问题。主要有两类，一个是如下：
> 
> `/home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:1441:3: 错误：‘PROTOBUF_FUTURE_MUST_USE_RESULT’不是一个类型名PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_domain();
> 
> /home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:1459:3: 错误：‘PROTOBUF_FUTURE_MUST_USE_RESULT’不是一个类型名PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_doc_string();
> 
> /home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:1474:3: 错误：‘PROTOBUF_FUTURE_MUST_USE_RESULT’不是一个类型名PROTOBUF_FUTURE_MUST_USE_RESULT ::onnx2trt_onnx::GraphProto* release_graph();
> 
> /home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:1661:3: 错误：‘PROTOBUF_FUTURE_MUST_USE_RESULT’不是一个类型名PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_key();
> 
> /home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:1679:3: 错误：‘PROTOBUF_FUTURE_MUST_USE_RESULT’不是一个类型名PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_value(); `
> 
> 还有一种如下：
> 
> `/home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:9207:87: 错误：成员函数‘onnx2trt_onnx::TypeProto_Spars
> eTensor* onnx2trt_onnx::TypeProto::release_sparse_tensor_type()’未在类‘onnx2trt_onnx::TypeProto’中声明
> inline ::onnx2trt_onnx::TypeProto_SparseTensor* TypeProto::release_sparse_tensor_type() {
> 
> /home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:9280:74: 错误：成员函数‘onnx2trt_onnx::TypeProto_Opaqu
> e* onnx2trt_onnx::TypeProto::release_opaque_type()’未在类‘onnx2trt_onnx::TypeProto’中声明
> inline ::onnx2trt_onnx::TypeProto_Opaque* TypeProto::release_opaque_type() {
> 
> /home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:9373:51: 错误：成员函数‘std::string* onnx2trt_onnx::Ty
> peProto::release_denotation()’未在类‘onnx2trt_onnx::TypeProto’中声明
> inline std::string* TypeProto::release_denotation() {
> 
> /home/lizheran/project/demo_tensorrt_inference/CenterNet-TensorRT-master/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.pb.h:9443:56: 错误：成员函数‘std::string* onnx2trt_onnx::Op
> eratorSetIdProto::release_domain()’未在类‘onnx2trt_onnx::OperatorSetIdProto’中声明
> inline std::string* OperatorSetIdProto::release_domain() {`
> 
> 这个看着像是onnx-tensorrt里面缺少头文件，请问po主怎么解决这个问题的啊

it seems that you should install the protobuf ( https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.8)
