### ISSUE TITLE
when use tensorrt7, bs=4 and the first image is correct and the others results is all 0 ?

### ISSUE THREAD

**Issue by sgzqc** [JosephChenHub/CenterNet-TensorRT#19]
你好！
非常感谢您这边提供的源码，使用该代码，1次推理多张图bs=4时，只有第一张图的结果是正确的。

**Comment by JosephChenHub** [comment]
> 你好！
> 非常感谢您这边提供的源码，使用该代码，1次推理多张图bs=4时，只有第一张图的结果是正确的。

could you provide the onnx model ?

**Comment by sgzqc** [comment]
@JosephChenHub  

You can get the onnx file from this link:

链接：https://pan.baidu.com/s/1chmvYIDAP6uAJXDq5fABlw 
提取码：v7vu

Thanks very much for your reply.

**Comment by JosephChenHub** [comment]
> @JosephChenHub
> 
> You can get the onnx file from this link:
> 
> 链接：https://pan.baidu.com/s/1chmvYIDAP6uAJXDq5fABlw
> 提取码：v7vu
> 
> Thanks very much for your reply.

Hi, have you noticed that our code fix the outputs' names to be ['hw', 'wh', 'reg']  while your model's outputs is ['hm_head', 'offset_head', 'hw_head'] ?  Please change the names and try again. 
https://github.com/JosephChenHub/CenterNet-TensorRT/blob/master/include/infer.hpp#L108

**Comment by sgzqc** [comment]
@JosephChenHub 
Hi,  I have update the onnx file output's name , you can visit the onnx file from here:

链接：https://pan.baidu.com/s/1RQkoq5skkQvT6KBY2c9MPQ 
提取码：sxct


we modify the infer.hpp like this:
![2021-08-10_121954](https://user-images.githubusercontent.com/15881893/128807948-7ca8a412-93dc-4839-a570-9973885e9bcc.png)

And the result is as below:

![2021-08-10_122051](https://user-images.githubusercontent.com/15881893/128807965-fa45a962-3ce5-460e-bafb-ec169d78adb5.png)

As show above,  wo use the same img to one batch, namely bs=4 .
However there is only the first img result is success while the others is all zero. Because we see output like this:
" we are process batch X"
" No objects detected in the image!"

**Comment by JosephChenHub** [comment]
> @JosephChenHub
> Hi, I have update the onnx file output's name , you can visit the onnx file from here:
> 
> 链接：https://pan.baidu.com/s/1RQkoq5skkQvT6KBY2c9MPQ
> 提取码：sxct
> 
> we modify the infer.hpp like this:
> ![2021-08-10_121954](https://user-images.githubusercontent.com/15881893/128807948-7ca8a412-93dc-4839-a570-9973885e9bcc.png)
> 
> And the result is as below:
> 
> ![2021-08-10_122051](https://user-images.githubusercontent.com/15881893/128807965-fa45a962-3ce5-460e-bafb-ec169d78adb5.png)
> 
> As show above, wo use the same img to one batch, namely bs=4 .
> However there is only the first img result is success while the others is all zero. Because we see output like this:
> " we are process batch X"
> " No objects detected in the image!"

Hi, your model has only 8 categories rather than 80 of coco, would you provide the class names  and the original test images ( 4 images are enough)?

**Comment by duohaoxue** [comment]
4 batch inferences，  I have the same result as you
batch_id: 0
3 detected in the image!
====> cls_id: 0
 score:0.59408 bbox:[591,311,659,380]
====> cls_id: 0
 score:0.55254 bbox:[1071,312,1194,398]
====> cls_id: 0
inference time is 335 ms
Gtk-Message: 21:10:39.232: Failed to load module "canberra-gtk-module"
batch_id: 1
 No  detected in the image!
batch_id: 2
 No  detected in the image!
batch_id: 3
 No  detected in the image!

**Comment by JosephChenHub** [comment]
> 4 batch inferences， I have the same result as you
> batch_id: 0
> 3 detected in the image!
> ====> cls_id: 0
> score:0.59408 bbox:[591,311,659,380]
> ====> cls_id: 0
> score:0.55254 bbox:[1071,312,1194,398]
> ====> cls_id: 0
> inference time is 335 ms
> Gtk-Message: 21:10:39.232: Failed to load module "canberra-gtk-module"
> batch_id: 1
> No detected in the image!
> batch_id: 2
> No detected in the image!
> batch_id: 3
> No detected in the image!

@sgzqc @duohaoxue  Hi, I have updated the code and the bug should be eliminated. The bug is caused by the indexing of the heat map: 
https://github.com/JosephChenHub/CenterNet-TensorRT/blob/master/src/decode.cu#L365, since the batch top-k outputs do not be aligned but have the format like
```
[batch-0]:  0.98, 0.95, 0.93, ..... 0.00
[batch-1]:  0.85, 0.80, 0.78, ... 
...
```

**Comment by duohaoxue** [comment]
> > 4 batch inferences， I have the same result as you
> > batch_id: 0
> > 3 detected in the image!
> > ====> cls_id: 0
> > score:0.59408 bbox:[591,311,659,380]
> > ====> cls_id: 0
> > score:0.55254 bbox:[1071,312,1194,398]
> > ====> cls_id: 0
> > inference time is 335 ms
> > Gtk-Message: 21:10:39.232: Failed to load module "canberra-gtk-module"
> > batch_id: 1
> > No detected in the image!
> > batch_id: 2
> > No detected in the image!
> > batch_id: 3
> > No detected in the image!
> 
> @sgzqc @duohaoxue Hi, I have updated the code and the bug should be eliminated. The bug is caused by the indexing of the heat map:
> https://github.com/JosephChenHub/CenterNet-TensorRT/blob/master/src/decode.cu#L365, since the batch top-k outputs do not be aligned but have the format like
> 
> ```
> [batch-0]:  0.98, 0.95, 0.93, ..... 0.00
> [batch-1]:  0.85, 0.80, 0.78, ... 
> ...
> ```


牛, Awesome

**Comment by sgzqc** [comment]
Thanks for your replay!
