### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by tcxia** [JosephChenHub/CenterNet-TensorRT#2]
Loading engine file:model/multi_pose_dla_3x.engine
size: 178699600
Create the engine from model/multi_pose_dla_3x.engine successfully!
i=0 tensor's name:input.1 dim:(3,512,512,1086353361) size:1036779520
i=1 tensor's name:520 dim:(1,128,128,1086353361) size:468992000
i=2 tensor's name:523 dim:(2,128,128,1086353361) size:937984000
i=3 tensor's name:526 dim:(2,128,128,1086353361) size:937984000
i=4 tensor's name:529 dim:(34,128,128,1086353361) size:18446744072475410432
i=5 tensor's name:532 dim:(17,128,128,1086353361) size:18446744073092481024
i=6 tensor's name:535 dim:(2,128,128,1086353361) size:937984000
cuda failure: /work/cppwork/tensorrt5/example/run_pose.cpp:216: 'out of memory'

code:
    for(int i = 0; i < nb_bindings; ++i) {
//        cout << "nb_bindings:" << nb_bindings << endl;
        CHECK_CUDA(cudaMalloc((void**)&buffers[i], sizeof(float) * engine_name_size[binding_names[i]].second));
    }

**Comment by JosephChenHub** [comment]
you should use a GPU card with larger memory or use FP16 mode.

**Comment by tcxia** [comment]
where is dcn_v2.hpp
