### ISSUE TITLE
Why need to get_affine_transform in preprocess?

### ISSUE THREAD

**Issue by PeppermintSummer** [JosephChenHub/CenterNet-TensorRT#20]
```
get_affine_transform(_h_inv_trans, center, scale, shift, 0, _runtime_input_dims[2], _runtime_input_dims[3], true); //! src -> dst
get_affine_transform(_h_inv_trans+6, center, scale, shift, 0, _net_out_hw[0], _net_out_hw[1], true); // det's
CHECK_CUDA(cudaMemcpy(_d_inv_trans, _h_inv_trans, sizeof(float) * 12, cudaMemcpyHostToDevice));
...
cuda_centernet_preprocess(ptr, _runtime_input_dims[0], _runtime_input_dims[1],
                _img_h, _img_w, _buffers[index], 
                _runtime_input_dims[2], _runtime_input_dims[3], 
                **_d_inv_trans**, nullptr, true, nullptr, true, 
                stream);
```
in `infer.hpp`

**Comment by JosephChenHub** [comment]
> ```
> get_affine_transform(_h_inv_trans, center, scale, shift, 0, _runtime_input_dims[2], _runtime_input_dims[3], true); //! src -> dst
> get_affine_transform(_h_inv_trans+6, center, scale, shift, 0, _net_out_hw[0], _net_out_hw[1], true); // det's
> CHECK_CUDA(cudaMemcpy(_d_inv_trans, _h_inv_trans, sizeof(float) * 12, cudaMemcpyHostToDevice));
> ...
> cuda_centernet_preprocess(ptr, _runtime_input_dims[0], _runtime_input_dims[1],
>                 _img_h, _img_w, _buffers[index], 
>                 _runtime_input_dims[2], _runtime_input_dims[3], 
>                 **_d_inv_trans**, nullptr, true, nullptr, true, 
>                 stream);
> ```
> 
> in `infer.hpp`

This operation functions as `resize`, and there exist parameters which can be calculated before.
