### ISSUE TITLE
416x416 inference box coordinate bit negative

### ISSUE THREAD

**Issue by duohaoxue** [JosephChenHub/CenterNet-TensorRT#22]
Hi，512x512 Correct inference ， but 416x416 inference box coordinate bit negative？

**Comment by JosephChenHub** [comment]
> Hi，512x512 Correct inference ， but 416x416 inference box coordinate bit negative？

could you provide the onnx file ?

**Comment by duohaoxue** [comment]
链接: https://pan.baidu.com/s/15IbWlyIDk7r2ZKZ6-M0yhg  密码: 3ne8
