### ISSUE TITLE
So how dose the speed performance like now?

### ISSUE THREAD

**Issue by Hezhexi2002** [JosephChenHub/CenterNet-TensorRT#23]

**Comment by Hezhexi2002** [comment]
> @JosephChenHub Thank you for your reply，I will try it in my spare time!

but I wonder if I could only use std::chrono to measure the pre-process+inference+post-process time?

**Comment by JosephChenHub** [comment]
> > @JosephChenHub Thank you for your reply，I will try it in my spare time!
> 
> but I wonder if I could only use std::chrono to measure the pre-process+inference+post-process time?

it's ok but make sure that the cuda streams are synchronized.

**Comment by Hezhexi2002** [comment]
> > > @JosephChenHub Thank you for your reply，I will try it in my spare time!
> > 
> > but I wonder if I could only use std::chrono to measure the pre-process+inference+post-process time?
> 
> it's ok but make sure that the cuda streams are synchronized.

ok，I will have a try
