### ISSUE TITLE
plugins_py/DCNv2问题

### ISSUE THREAD

**Issue by rolan123** [JosephChenHub/CenterNet-TensorRT#24]
您好，
请问plugins_py/DCNv2相比于原版的DCNv2_pytorch1.0，除了test_onnx.py，修改了哪些地方呢？
如果我想用最新版本的pytorch，所以使用了DCNv2_last版本，我该怎么修改成plugins_py/DCNv2中类似的代码？
万分感谢！

**Comment by JosephChenHub** [comment]
> > > 我所使用的版本是[https://github.com/jinfagang/DCNv2_latest.git，使用torch1.9编译通过](https://github.com/jinfagang/DCNv2_latest.git%EF%BC%8C%E4%BD%BF%E7%94%A8torch1.9%E7%BC%96%E8%AF%91%E9%80%9A%E8%BF%87)
> > 
> > 
> > please refer to the plugin https://github.com/JosephChenHub/CenterNet-TensorRT/tree/master/onnx-tensorrt/plugin/DCN we remove the dependency of libtorch in the implementation of DCN .
> 
> 您的README中写： replace the CenterNet/src/lib/models/networks/DCNv2 with plugins_py/DCNv2. To obtain the onnx file 我发现plugins_py/DCNv2中依旧采用了ATen， 请问是否应该修改为，用onnx-tensorrt/plugin/DCN来代替？

the `plugins_py/DCNv2` is set for exporting the onnx file  via pytorch.

**Comment by rolan123** [comment]
如果我修改https://github.com/JosephChenHub/CenterNet-TensorRT/blob/master/onnx-tensorrt/builtin_op_importers.cpp#L3905，
将其改为DEFINE_BUILTIN_OP_IMPORTER(DCNv2) {
原来的错误消失，新的错误是：
Parsing node:  [DCNv2]
 node.input:243
 node.input:248
 node.input:249
 node.input:deconv_layers.0.weight
 node.input:deconv_layers.0.bias
Searching for input:243 count: 1
Searching for input:248 count: 1
Searching for input:249 count: 1
Searching for input:deconv_layers.0.weight count: 1
Searching for input:deconv_layers.0.bias count: 1
 tensor-input:[1,512,16,16,]
 tensor-offset:[1,18,16,16,]
 tensor-mask:[1,9,16,16,]
 tensor-weight:[256,512,3,3,]
 tensor-bias:[256,]
terminate called after throwing an instance of 'std::out_of_range'
  what():  Attribute not found: deformable_groups
Aborted (core dumped)

**Comment by JosephChenHub** [comment]
> (＾－＾)我修改了参数，搞定了！开心 那么有一个新的问题：请问data.txt存放的是图片的像素矩阵吗？

按行存储图片名，例如:
```
/mnt/data/00001.jpg
/mnt/data/00002.jpg
/mnt/data/addgg.jpg
....
```

**Comment by rolan123** [comment]
OK了，十分感谢
Thanks♪(･ω･)ﾉ

**Comment by wangxj2014** [comment]
> 如果我修改[https://github.com/JosephChenHub/CenterNet-TensorRT/blob/master/onnx-tensorrt/builtin_op_importers.cpp#L3905，](https://github.com/JosephChenHub/CenterNet-TensorRT/blob/master/onnx-tensorrt/builtin_op_importers.cpp#L3905%EF%BC%8C) 将其改为DEFINE_BUILTIN_OP_IMPORTER(DCNv2) { 原来的错误消失，新的错误是： Parsing node: [DCNv2] node.input:243 node.input:248 node.input:249 node.input:deconv_layers.0.weight node.input:deconv_layers.0.bias Searching for input:243 count: 1 Searching for input:248 count: 1 Searching for input:249 count: 1 Searching for input:deconv_layers.0.weight count: 1 Searching for input:deconv_layers.0.bias count: 1 tensor-input:[1,512,16,16,] tensor-offset:[1,18,16,16,] tensor-mask:[1,9,16,16,] tensor-weight:[256,512,3,3,] tensor-bias:[256,] terminate called after throwing an instance of 'std::out_of_range' what(): Attribute not found: deformable_groups Aborted (core dumped)


您好，我遇到了一样的问题，麻烦问下您是怎么解决的？修改了哪些参数？谢谢
