### ISSUE TITLE
onnx-tensorrt/plugin make error

### ISSUE THREAD

**Issue by austinmw** [JosephChenHub/CenterNet-TensorRT#4]
Hi, thanks for this repo. Which cmake version are you using for this project? I can cmake with:

```bash
cd /root/CenterNet-TensorRT/onnx-tensorrt/plugin/build
cmake .. -DTENSORRT_ROOT=/opt/TensorRT-7.0.0.11/lib \
-DTENSORRT_INCLUDE_DIR=/opt/TensorRT-7.0.0.11/include \
-DTorch_DIR=/root/miniconda3/lib/python3.7/site-packages/torch/share/cmake/Torch
```
But `make -j` results in:

> nvcc fatal   : redefinition of argument 'std'

I tried deleting `-std=c++11` from `plugin/CMakeLists.txt`, but then get a ton of errors (91), for example:

> /root/CenterNet-TensorRT/onnx-tensorrt/plugin/Resize_v1/ResizeBilinear.hpp(178): error: expected a ";"
> 
> /root/CenterNet-TensorRT/onnx-tensorrt/plugin/Resize_v1/ResizeBilinear.hpp(180): error: qualified name is not allowed
> 
> /root/CenterNet-TensorRT/onnx-tensorrt/plugin/Resize_v1/ResizeBilinear.hpp(180): error: explicit type is missing ("int" assumed)
> 
> /root/CenterNet-TensorRT/onnx-tensorrt/plugin/Resize_v1/ResizeBilinear.hpp(180): error: expected a ";"

Any help would be greatly appreciated.

**Comment by tcxia** [comment]
I have a similar problem？

libmynvonnxparser_static.a(builtin_op_importers.cpp.o): In function `MyUpsamplePluginCreator::getFieldNames()':
builtin_op_importers.cpp:(.text._ZN23MyUpsamplePluginCreator13getFieldNamesEv[_ZN23MyUpsamplePluginCreator13getFieldNamesEv]+0x3): undefined reference to `MyUpsamplePluginCreator::_mFC'

**Comment by JosephChenHub** [comment]
> Hi, thanks for this repo. Which cmake version are you using for this project? I can cmake with:
> 
> ```shell
> cd /root/CenterNet-TensorRT/onnx-tensorrt/plugin/build
> cmake .. -DTENSORRT_ROOT=/opt/TensorRT-7.0.0.11/lib \
> -DTENSORRT_INCLUDE_DIR=/opt/TensorRT-7.0.0.11/include \
> -DTorch_DIR=/root/miniconda3/lib/python3.7/site-packages/torch/share/cmake/Torch
> ```
> 
> But `make -j` results in:
> 
> > nvcc fatal   : redefinition of argument 'std'
> 
> I tried deleting `-std=c++11` from `plugin/CMakeLists.txt`, but then get a ton of errors (91), for example:
> 
> > /root/CenterNet-TensorRT/onnx-tensorrt/plugin/Resize_v1/ResizeBilinear.hpp(178): error: expected a ";"
> > /root/CenterNet-TensorRT/onnx-tensorrt/plugin/Resize_v1/ResizeBilinear.hpp(180): error: qualified name is not allowed
> > /root/CenterNet-TensorRT/onnx-tensorrt/plugin/Resize_v1/ResizeBilinear.hpp(180): error: explicit type is missing ("int" assumed)
> > /root/CenterNet-TensorRT/onnx-tensorrt/plugin/Resize_v1/ResizeBilinear.hpp(180): error: expected a ";"
> 
> Any help would be greatly appreciated.

The version of CMake I used is 3.13. For older CMake, it may result in this problem.

**Comment by JosephChenHub** [comment]
> undefined reference to

Hi. This problem like 'undefined reference to  XXXX' generally means **linking errors**.  some tips:
1. check **the library path** in your project; 
2. check the header file whether correct or **included**.

**Comment by tcxia** [comment]
> > undefined reference to
> 
> Hi. This problem like 'undefined reference to XXXX' generally means **linking errors**. some tips:
> 
> 1. check **the library path** in your project;
> 2. check the header file whether correct or **included**.
o
Hi, I have compiled and passed, but  I cannot find the plug-in DCNv2 transferring to onnx

**Comment by JosephChenHub** [comment]
> > > undefined reference to
> > 
> > 
> > Hi. This problem like 'undefined reference to XXXX' generally means **linking errors**. some tips:
> > 
> > 1. check **the library path** in your project;
> > 2. check the header file whether correct or **included**.
> >    o
> >    Hi, I have compiled and passed, but  I cannot find the plug-in DCNv2 transferring to onnx

Since the onnx-tensorrt uses the factory mode, you should register your custom op in the file `onnx-tensorrt/builtin_op_importers.cpp'. In this project, the DCN op was defined as  `DEFINE_BUILTIN_OP_IMPORTER(DCN) {...} '. For converting the torch model to onnx file, you may refer to the `master/DCNv2/test_onnx.py'.

**Comment by tcxia** [comment]
> > > > undefined reference to
> > > 
> > > 
> > > Hi. This problem like 'undefined reference to XXXX' generally means **linking errors**. some tips:
> > > 
> > > 1. check **the library path** in your project;
> > > 2. check the header file whether correct or **included**.
> > >    o
> > >    Hi, I have compiled and passed, but  I cannot find the plug-in DCNv2 transferring to onnx
> 
> Since the onnx-tensorrt uses the factory mode, you should register your custom op in the file 'onnx-tensorrt/builtin_op_importers.cpp'. In this project, the DCN op was defined as 'DEFINE_BUILTIN_OP_IMPORTER(DCN) {...} '. For converting the torch model to onnx file, you may refer to the 'master/DCNv2/test_onnx.py'.

I read the code `onnx-tensorrt/builtin_op_importers.cpp`, which is registered, but the conversion tip has no plugin
