### ISSUE TITLE
some image may cause core

### ISSUE THREAD

**Issue by xiexuliunian** [JosephChenHub/CenterNet-TensorRT#5]
Thanks for your work.
I change the classes to 2
when I use some image it is ok
![image](https://user-images.githubusercontent.com/24749356/88375689-9a113f00-cdce-11ea-9346-0a8e8f39b883.png)
but when I change another pic....
![image](https://user-images.githubusercontent.com/24749356/88375749-b7dea400-cdce-11ea-8877-e902b1fbd808.png)
Can anyone help? I just change the num_classes=2,Do I need to modify other place?

**Comment by JosephChenHub** [comment]
have you ever checked the integrity of the image `44.jpg`?

**Comment by JosephChenHub** [comment]
> Thanks for your work.
> I change the classes to 2
> when I use some image it is ok
> ![image](https://user-images.githubusercontent.com/24749356/88375689-9a113f00-cdce-11ea-9346-0a8e8f39b883.png)
> but when I change another pic....
> ![image](https://user-images.githubusercontent.com/24749356/88375749-b7dea400-cdce-11ea-8877-e902b1fbd808.png)
> Can anyone help? I just change the num_classes=2,Do I need to modify other place?

have you ever checked the integrity of the image 44.jpg?

**Comment by xiexuliunian** [comment]
yeah,I have sure the image 44.jpg is just a simple image .It can be read and write by opencv 
I find that when the pic contains two different labels object,the error will happend,but when the pic only contains just one label of object ,the output will be normal.So I want to know when I change the classes from 80 to 2 and have got the converted trt model ,where should I to modify to got the correct output.
Thanks!!! for your reply。

**Comment by xiexuliunian** [comment]
why closed？
