### ISSUE TITLE
error: Unsupported ONNX data type: UINT8 (2)

### ISSUE THREAD

**Issue by CaptainJohansson** [JosephChenHub/CenterNet-TensorRT#7]
this error is caused by this line : keep = (hmax==hm).float(), since TensorRT' Cast operation does not support the transformation from UINT8 to Float 32. do you have any suggestion to solve this problem?

**Comment by JosephChenHub** [comment]
> this error is caused by this line : keep = (hmax==hm).float(), since TensorRT' Cast operation does not support the transformation from UINT8 to Float 32. do you have any suggestion to solve this problem?

which version of PyTorch and TensorRT do you use?  In my previous environment, this operation has been supported without errors.

**Comment by CaptainJohansson** [comment]
the used version of pytorch is 1.1.0 and tensorrt is 7.0.0. the different between your enviroments and my enviroments is the pytorch version.

**Comment by JosephChenHub** [comment]
> the used version of pytorch is 1.1.0 and tensorrt is 7.0.0. the different between your enviroments and my enviroments is the pytorch version.

you may need to update your pytorch, otherwise you should write an implementation of this operation in the decode stage.

**Comment by CaptainJohansson** [comment]
ok, I will try to update my Pytorch. Thanks for your answer!
