### ISSUE TITLE
显存泄露问题

### ISSUE THREAD

**Issue by lujun-wuhan** [JosephChenHub/CenterNet-TensorRT#9]
你好，你所做的工作非常出色，我把代码修改了一下，循环预测视频，发现显存泄露问题很严重，新版本cuda的显存管理改成了C++的智能指针，好像仍然没有解决这个问题，希望你能持续跟踪这个问题

**Comment by JosephChenHub** [comment]
> 经测试，TensortRT v7.0 v7.7都有这个问题

建议用 cuda-gdb 调试进程，查看调用栈
